language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libpcre3-dev
      - libflac-dev
      - libid3tag0-dev
      - libvorbis-dev
      - libmagic-dev
      - pkg-config
script: ./autogen.sh && ./configure && make
